### ISSUE TITLE
Double Months 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/grommet-roadmap#4]
It shows March twice until you navigate forward. Then navigating back it shows February and has the correct view. 

![image](https://user-images.githubusercontent.com/17712467/94708151-81a72e80-0301-11eb-9214-63c16ea4be77.png)

**Comment by ShimiSun** [comment]
@MikeWalrath Why is this issue reported on grommet-roadmap vs grommet as a bug?

**Comment by MikeWalrath** [comment]
Eric asked me to file any issues for the roadmap in the this repo. Is there a way to verify if its a Grommet bug vs a grommet roadmap tool bug? https://roadmap.grommet.io/hpe-design-system-roadmap-mike-walrath-hpe-com

**Comment by ShimiSun** [comment]
@MikeWalrath lets discuss it on the staff call.
